# Generated by Django 4.1.4 on 2023-01-05 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_age', models.CharField(max_length=256)),
                ('to_age', models.CharField(max_length=256)),
                ('period', models.CharField(max_length=256)),
                ('from_ageAr', models.CharField(max_length=256)),
                ('to_ageAr', models.CharField(max_length=256)),
                ('periodAr', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('note', models.TextField(max_length=1000)),
                ('noteAr', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
