# Generated by Django 4.1.4 on 2023-01-05 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('titleAr', models.CharField(max_length=256)),
                ('packageType', models.CharField(choices=[('InBound', 'InBound'), ('OutBound', 'OutBound')], default='InBound', max_length=30)),
                ('packageTypeAr', models.CharField(choices=[('ضمن القطر', 'ضمن القطر'), ('خارج القطر', 'خارج القطر')], default='ضمن القطر', max_length=30)),
                ('country', models.CharField(blank=True, max_length=256)),
                ('countryAr', models.CharField(blank=True, max_length=256)),
                ('photo', models.ImageField(upload_to='packages/')),
                ('packageProgram', models.TextField(max_length=2000)),
                ('packageProgramAr', models.TextField(max_length=2000)),
                ('sdate', models.DateTimeField()),
                ('edate', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackageImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='packages/')),
                ('Package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
            ],
        ),
    ]
