# Generated by Django 4.1.4 on 2023-01-05 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_from', models.CharField(max_length=256)),
                ('drop_off_to', models.CharField(max_length=256)),
                ('ride_fromAr', models.CharField(max_length=256)),
                ('drop_off_toAr', models.CharField(max_length=256)),
                ('photo', models.ImageField(upload_to='cars/')),
                ('Persons_number', models.IntegerField()),
                ('bags_number', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
